"""Added fields to Video model

Revision ID: 3c8c846ad27e
Revises: e323458bd9fd
Create Date: 2025-03-07 12:07:29.842155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8c846ad27e'
down_revision: Union[str, None] = 'e323458bd9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('upvote_count', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('video_link', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumbnail_url')
    op.drop_column('videos', 'video_link')
    op.drop_column('videos', 'comment_count')
    op.drop_column('videos', 'upvote_count')
    op.drop_column('videos', 'view_count')
    # ### end Alembic commands ###
