"""Added video storage

Revision ID: e323458bd9fd
Revises: e226a777a928
Create Date: 2025-03-07 12:04:28.684119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e323458bd9fd'
down_revision: Union[str, None] = 'e226a777a928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_interactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_interactions', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('user_interactions_video_id_fkey', 'user_interactions', type_='foreignkey')
    op.drop_constraint('user_interactions_user_id_fkey', 'user_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'user_interactions', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_interactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('videos', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'created_at')
    op.drop_constraint(None, 'user_interactions', type_='foreignkey')
    op.drop_constraint(None, 'user_interactions', type_='foreignkey')
    op.create_foreign_key('user_interactions_user_id_fkey', 'user_interactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_interactions_video_id_fkey', 'user_interactions', 'videos', ['video_id'], ['id'])
    op.alter_column('user_interactions', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_interactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
